[package]
name = "imkitchen-notification"
version = "0.13.1"
edition.workspace = true
authors.workspace = true

[dependencies]
askama = { workspace = true }
lettre = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
rust-i18n = { workspace = true }
time = { workspace = true }
evento.workspace = true
imkitchen-shared = { path = "../shared", version = "0.13.1" }
