[package]
name = "imkitchen-user"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
evento.workspace = true
bincode.workspace = true
anyhow.workspace = true
validator.workspace = true
argon2.workspace = true
sqlx.workspace = true
tokio.workspace = true
ulid.workspace = true
sqlx_migrator.workspace = true
sea-query.workspace = true
sea-query-sqlx.workspace = true
async-trait.workspace = true
