[package]
name = "imkitchen-user"
version = "0.12.4"
edition.workspace = true
authors.workspace = true

[dependencies]
evento.workspace = true
bincode.workspace = true
anyhow.workspace = true
validator = { workspace = true, optional = true }
argon2.workspace = true
sqlx = { workspace = true, optional = true }
strum.workspace = true
time = { workspace = true, optional = true }
ulid = { workspace = true, optional = true }
sea-query.workspace = true
sea-query-sqlx.workspace = true
cfg-if.workspace = true
serde.workspace = true
imkitchen-shared = { path = "../shared", version = "0.12.4" }
imkitchen-db = { path = "../db", version = "0.12.4", optional = true }
imkitchen-recipe = { path = "../recipe", version = "0.12.4", default-features = false, optional = true }

[dev-dependencies]
tokio.workspace = true
temp-dir.workspace = true
futures.workspace = true

[features]
default = ["full", "imkitchen-recipe"]
full = ["sqlx", "validator", "imkitchen-db", "time", "ulid"]
