[package]
name = "imkitchen-user"
version = "0.9.4"
edition.workspace = true
authors.workspace = true

[dependencies]
evento.workspace = true
bincode.workspace = true
anyhow.workspace = true
validator.workspace = true
argon2.workspace = true
sqlx.workspace = true
tokio.workspace = true
sea-query.workspace = true
sea-query-sqlx.workspace = true
serde.workspace = true
imkitchen-shared = { path = "../shared", version = "0.9.4" }
imkitchen-db = { path = "../db", version = "0.9.4" }
