[package]
name = "imkitchen-recipe"
version = "0.10.0"
edition.workspace = true
authors.workspace = true

[dependencies]
evento.workspace = true
bincode.workspace = true
anyhow.workspace = true
validator.workspace = true
sqlx.workspace = true
strum.workspace = true
serde.workspace = true
tokio.workspace = true
sha3.workspace = true
imkitchen-shared = { path = "../shared", version = "0.10.0" }
imkitchen-db = { path = "../db", version = "0.10.0" }

[dev-dependencies]
imkitchen-user = { path = "../user", version = "0.10.0" }
