[package]
name = "imkitchen-recipe"
version = "0.9.4"
edition.workspace = true
authors.workspace = true

[dependencies]
evento.workspace = true
bincode.workspace = true
anyhow.workspace = true
validator.workspace = true
sqlx.workspace = true
strum.workspace = true
tokio.workspace = true
sha3.workspace = true
imkitchen-shared = { path = "../shared", version = "0.9.4" }
imkitchen-db = { path = "../db", version = "0.9.4" }

[dev-dependencies]
imkitchen-user = { path = "../user", version = "0.9.4" }
