[package]
name = "imkitchen-recipe"
version = "0.12.2"
edition.workspace = true
authors.workspace = true

[dependencies]
evento.workspace = true
bincode.workspace = true
anyhow.workspace = true
validator = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
strum.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
cfg-if.workspace = true
sea-query.workspace = true
sea-query-sqlx.workspace = true
imkitchen-shared = { path = "../shared", version = "0.12.2" }
imkitchen-db = { path = "../db", version = "0.12.2", optional = true }

[dev-dependencies]
tokio.workspace = true
temp-dir.workspace = true

[features]
default = ["full"]
full = ["sqlx", "validator", "imkitchen-db"]
