[package]
name = "imkitchen-mealplan"
version = "0.10.0"
edition.workspace = true
authors.workspace = true

[dependencies]
evento.workspace = true
bincode.workspace = true
anyhow.workspace = true
validator = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
time = { workspace = true, optional = true }
cfg-if.workspace = true
strum.workspace = true
serde.workspace = true
sea-query.workspace = true
sea-query-sqlx.workspace = true
imkitchen-shared = { path = "../shared", version = "0.10.0" }
imkitchen-db = { path = "../db", version = "0.10.0", optional = true }
imkitchen-recipe = { path = "../recipe", version = "0.10.0", default-features = false, optional = true }

[dev-dependencies]
tokio.workspace = true
temp-dir.workspace = true
futures.workspace = true

[features]
default = ["full", "imkitchen-recipe"]
full = ["sqlx", "validator", "imkitchen-db", "time"]
